import { chromium } from 'playwright';
import { readFileSync, writeFileSync } from 'fs';

console.log('Abriendo browser para login en Facebook...');
console.log('1. Hacé login manualmente en la ventana');
console.log('2. Cuando termines, cerrá la pestaña\n');

const browser = await chromium.launch({ headless: false, channel: 'chrome' });
const context = await browser.newContext();
const page = await context.newPage();

await page.goto('https://www.facebook.com/login');

page.on('close', async () => {
  try {
    const state = await context.storageState();
    const b64 = Buffer.from(JSON.stringify(state)).toString('base64');

    // Append to .env (or update if exists)
    const envPath = '.env';
    let envContent = '';
    try { envContent = readFileSync(envPath, 'utf-8'); } catch { /* no .env yet */ }

    if (envContent.includes('FB_STORAGE_STATE=')) {
      envContent = envContent.replace(/FB_STORAGE_STATE=.*/g, `FB_STORAGE_STATE=${b64}`);
    } else {
      envContent += `\n# Facebook session cookies (auto-generated by scripts/fb-login.js)\nFB_STORAGE_STATE=${b64}\n`;
    }

    writeFileSync(envPath, envContent);
    console.log('\n✓ FB_STORAGE_STATE guardado en .env');
    console.log('Para EasyPanel, copiar el valor de FB_STORAGE_STATE del .env');
  } catch (e) {
    console.error('Error guardando estado:', e.message);
  } finally {
    await browser.close().catch(() => {});
    process.exit(0);
  }
});
